[package]
name = "pingme"
version = "0.1.0"
edition = "2021"

[dependencies]
ngrok = { version="0.13", features=["axum"] }
tokio = { version = "1.26", features = ["full"] }
axum = "0.6"
http = "0.2.8"
notify-rust = "4.11.3"
reqwest = "0.12.9"
anyhow = "1.0.92"
